# Generated by Django 4.0.4 on 2022-05-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_to',
            field=models.CharField(default='Jhon doe', max_length=255),
            preserve_default=False,
        ),
    ]
