# Generated by Django 4.0 on 2022-08-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_interval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
