# Generated by Django 4.0 on 2022-08-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_messages_message_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_type',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
